### ISSUE TITLE
Update results with new elections database dump

### ISSUE THREAD

**Issue by ghing** [openelections/openelections-data-wa#2]
Nick Pharis from the Washington SoS, sent me an updated database dump file. This needs to be incorporated into this package.

Newly baked files with correct date names should be as follows:
- 20001104__wa__general.csv -> 20001107__wa__general.csv
- 20000901__wa__primary.csv -> 20000919__wa__primary.csv
- 20011101__wa__general.csv -> 20011106__wa__general.csv
- 20041109__wa__general.csv -> 20041102__wa__general.csv
- 20040921__wa__primary.csv -> 20040914__wa__primary.csv

**Subtasks**
- [x] Update loading script to handle MM/DD/YYYY dates as well as YYYY-MM-DD because that's what's in the new file.
- [x] Regenerate files with correct date names
- [x] Remove old files

This is related to https://github.com/openelections/core/issues/148
